### ISSUE TITLE
动画资产获取

### ISSUE THREAD

**Issue by thenighthunter0** [endink/VActor#1]
你好，感谢您的软件

我想提取出动画序列，比如视频中动作的动画序列，进而驱动其他的虚拟人物，

您的软件有后续的更新计划吗？

或者有其他建议，比如在插件基础上，自己去实现使用？

**Comment by endink** [comment]
我正在开发 BVH 动补数据导出功能，不知道这能不能帮到你，由于软件是引擎中立的，我为 UE 开发一个功能，可能需要为 Unity 开发一个功能，因为是用爱发电项目，暂时没有精力去做引擎端的连接器，我理解的没错的话，你所说的动画序列是 UE， 那么你可以尝试我的 MediaPipe4U 插件直接去驱动角色，这样你只需要在 UE 里 Record 这些动画就能得到动画序列。

**Comment by endink** [comment]
BTW: 感谢使用 github 提交反馈，这里的反馈我都会尽最大努力实现

**Comment by thenighthunter0** [comment]
万分感谢您的回复，因为我是cv算法工程师，对于ue5了解较少，目前只会mixamo骨骼重定向驱动metahuman，我再去深入学习ue相关，以及您的插件，万分感谢。

**Comment by endink** [comment]
MediaPipe4U 能够驱动任意的“人类”骨骼模型而不需要重定向，我相信 Mixiamo 也同样可以直接驱动，这里有个驱动 CC4 的例子：

https://www.bilibili.com/video/BV1CY411o7kH/

在 UE Editor 中驱动角色后可以通过 Recorder 录制动画来得到动画序列

**Comment by thenighthunter0** [comment]
太感谢了
