### ISSUE TITLE
根运动

### ISSUE THREAD

**Issue by thenighthunter0** [endink/VActor#2]
发现里面做运动时，以屁股为根节点，没有相对于世界坐标系。
我之前做重定向时，也遇到过这个问题，root到屁股那个链条，平移模式改为全局缩放即可。
不过如果作为直播等设定的话，这样也没有问题。

**Comment by endink** [comment]
这个问题和代码的结构有点关系，root motion 实现上需要改很多代码，如果是导出 BVH 需求的话我可以在导出时候把变换移动到 root 骨骼

**Comment by endink** [comment]
能描述一下场景？你是想在重定向时候得到根运动？

**Comment by thenighthunter0** [comment]
是的，我想把一些真人动作映射到，虚拟人物，驱动虚拟人物可以运动。
没有根运动的话，动作会比较奇怪。比如做个摔倒，结果虚拟人物是摔倒在空中。
目的是得到这些运动序列，进而驱动metahuman等人物。

**Comment by endink** [comment]
先Mark，这个可以很快添加，但是目前的位移非常麻烦，你需要标定位置，目前只设计了倒计时，没有手动标定，所以你用起来非常难用，我找不到一个好的办法来标定，或许需要增加一个视频几分几秒作为初始位置标定？

**Comment by thenighthunter0** [comment]
目前插件有根运动的吗，我还没研究到

**Comment by endink** [comment]
没有根运动，但是有位移，就是你说的 Hip 在位移

**Comment by thenighthunter0** [comment]
嗯嗯，了解，感谢

**Comment by endink** [comment]
如果你是用视频文件动作捕捉，那么要处理位移标定问题目前的版本只有一个方案，就是你设置标定倒计时，然后处理视频文件（用剪映类似的工具）在倒计时附近的1~2秒视频上放置你想用于标定位置的图像或截图，总之，非常麻烦，因为现在的设计只考虑了摄像头动补，到计时对于摄像头的人来说只要 XX 秒不要动就可以了，但是对于视频文件，这是个非常难以获得很好的体验的问题，最直接的或许是给我一张图片，让我标定，然后你自己截图，后面才会增加图片标定功能了，目前精力在 IK 和扭曲矫正优化部分，现在膝盖还是有点扭曲

**Comment by thenighthunter0** [comment]
嗯嗯，可以使用标定倒计时的话，这个我可以做，因为我本身就是做计算机视觉算法的，视频处理不是问题。你先忙，加油
