### ISSUE TITLE
UE5.03里获取不到VActor的信息呢

### ISSUE THREAD

**Issue by jingxicaishi** [endink/VActor#3]
启动了VActor捕捉，UE 有插件，但是显示未激活，信息没有传进UE呢？
![D8ADB01F-9D91-46d0-8CC2-83C26C61203D](https://user-images.githubusercontent.com/27883086/205434759-fbd6a80d-a7ad-42b5-be7b-4651ffa29df1.png)
![2](https://user-images.githubusercontent.com/27883086/205434769-abab308c-bde3-4464-9b15-4166d1959886.png)

**Comment by jingxicaishi** [comment]
目的是想用Vactor驱动 UE里的metahuan上半身动作，可能会出现的问题是什么呢？

**Comment by jingxicaishi** [comment]
主要是想用Vactor驱动UE5里的metahuman上半身动作，但是好像信息没有传递进UE，没传进来信息可能是因为什么引起的呢？

**Comment by endink** [comment]
这个是独立软件啊，和 UE5 不会连动的，你要在 UE5 里使用你要用 mediapipe4U 插件，不需要外挂任何程序的

**Comment by endink** [comment]
Mediapip4U 和 VACTOR 没有任何关系， livelink 要在程序运行起来以后才会显示激活

**Comment by endink** [comment]
请不要同时使用 Vactor 和 Mediapipe4U, livelink 会端口冲突

**Comment by jingxicaishi** [comment]
那要驱动 metahuan的人物，需要在你代码基础上来改，不能直接用啊，，，，我以为他是个捕获程序，捕获的信息传回UE里，通过mediapipe4U接收，在UE里改改动画名字关联就行了...

**Comment by endink** [comment]
放入 MediaPipeLiveLinkComponent ,  然后做一个继承于 MediaPipeAnimInstance 的动画蓝图，蓝图放入标准 LiveLink 节点，启动程序就可以了，不需要改什么，算了，等有空我做一期面补教程吧，因为效果并不好，所以这块我没有主推，你不能驱动可能因为你的动画蓝图没有继承于 MediaPipeAnimInstance ， 这是必要条件

**Comment by endink** [comment]
你觉得 VActor 那种面补效果能接受？效果很差啊

**Comment by jingxicaishi** [comment]
想用Acotr来捕捉上半身，苹果手机自带的功能捕捉面部

**Comment by jingxicaishi** [comment]
我试了用CC的原型，新建了一个项目，也是不会动呢。是不是开摄像头那些没做，我看视频里没有，

**Comment by endink** [comment]
拜托阅读文档，下载demo 程序
