### ISSUE TITLE
软件报错，不能动普视频

### ISSUE THREAD

**Issue by hellosorry** [endink/VActor#5]
[](url)
<img width="962" alt="Snipaste_2022-12-08_14-01-44" src="https://user-images.githubusercontent.com/46017769/206371112-1e7f5027-e183-4fe0-a3d3-6046afbf68b8.png">

**Comment by endink** [comment]
看到了，感谢反馈，这个是加载模型时候还是？大概是打包时候编辑器里不小心开启了纹理流送

**Comment by hellosorry** [comment]
我是打开软件就这样

**Comment by hellosorry** [comment]
> 看到了，感谢反馈，这个是加载模型时候还是？大概是打包时候编辑器里不小心开启了纹理流送

我是打开软件就这样

**Comment by endink** [comment]
下次打包会仔细检查设置，目前手动修复方案：

找到软件目录下的 **VActor/Config/DefaultEngine.ini**
再 **[/Script/Engine.RendererSettings]** 下面修改
```
r.TextureStreaming=False
```

如果这样不行，改成这样
```
r.TextureStreaming=True
r.Streaming.PoolSize=1000
```

**Comment by hellosorry** [comment]
> 下次打包会仔细检查设置，目前手动修复方案：
> 
> 找到软件目录下的 **VActor/Config/DefaultEngine.ini** 再 **[/Script/Engine.RendererSettings]** 下面修改
> 
> ```
> r.TextureStreaming=False
> ```
> 
> 如果这样不行，改成这样
> 
> ```
> r.TextureStreaming=True
> r.Streaming.PoolSize=1000
> ```

哥哥，你方便的话重新上传下吧，这个目录和文件我在软件中找不到呀

**Comment by endink** [comment]
对不起，我的错，想成开发环境配置了， 目录  VActor\Saved\Config\Windows 下找到文件 GameUserSettings.ini

添加如下：
```
[/Script/Engine.RendererSettings]
r.TextureStreaming=False
```

如果不起作用添加如下：

```
[/Script/Engine.RendererSettings]
r.TextureStreaming=True
r.Streaming.PoolSize=1000
```

**Comment by endink** [comment]
我现在电脑不在身边

**Comment by hellosorry** [comment]
> 我现在电脑不在身边

等你有时间解决下把，我试了还是不行，
<img width="729" alt="Snipaste_2022-12-08_15-31-08" src="https://user-images.githubusercontent.com/46017769/206386983-9be7341a-6dce-4ccf-84e4-2d8be0a865a5.png">
<img width="642" alt="Snipaste_2022-12-08_15-35-07" src="https://user-images.githubusercontent.com/46017769/206387000-9b500ee8-8f32-44b3-804c-bbd9b811034f.png">

**Comment by endink** [comment]
好的，非常奇怪的问题

**Comment by endink** [comment]
请尝试 20221209 版本， 问题应该已修复

**Comment by hellosorry** [comment]
> 请尝试 20221209 版本， 问题应该已修复

非常感谢更新，我刚下载了1209版，问题还是存在，我想知道是我个例还是？这个软件还是需要下载什么依存组件

**Comment by endink** [comment]
嗯？看起来是个例，还是同样的问题？你内存多大？
________________________________

**Comment by endink** [comment]
还是同样的问题？

**Comment by hellosorry** [comment]
> 还是同样的问题？

内存8G，还是同样的问题，经我测试摄像头动捉没问题可以用，视频动画录制用不了
<img width="960" alt="Snipaste_2022-12-09_20-24-37" src="https://user-images.githubusercontent.com/46017769/206702012-fb67d084-b233-4a4a-bfb0-642b58afaeff.png">

**Comment by hellosorry** [comment]
> 还是同样的问题？

我看你视频，这个应该视频动普可以直接导入，不用挂OBS

**Comment by endink** [comment]
麻烦给出日志文件

**Comment by endink** [comment]
VActor\Saved\Logs 最新的一个文件

**Comment by hellosorry** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anders ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 晚上8:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [endink/VActor] 软件报错，不能动普视频 (Issue #5)





 
VActor\Saved\Logs 最新的一个文件

**Comment by endink** [comment]
有这个错误是会有问题的，这个是纹理内存池爆了，可能会造成某些地方显示出问题

**Comment by endink** [comment]
这个软件大概要占用 1.5 G 内存，你是不是机器内存满了呢

**Comment by endink** [comment]
你的视频分辨率是不是太高了~~ 你视频文件是多大，分辨率多大呢

**Comment by hellosorry** [comment]
> 你的视频分辨率是不是太高了~~ 你视频文件是多大，分辨率多大呢

<img width="329" alt="Snipaste_2022-12-09_20-36-15" src="https://user-images.githubusercontent.com/46017769/206704125-44a1ebce-9f37-4e7a-89b9-e2e189180efc.png">

**Comment by hellosorry** [comment]
> 这个软件大概要占用 1.5 G 内存，你是不是机器内存满了呢

<img width="962" alt="Snipaste_2022-12-09_20-35-16" src="https://user-images.githubusercontent.com/46017769/206704252-b3c0842f-c495-47c9-a616-aefabf4755f0.png">

**Comment by endink** [comment]
看起来环境是 OK 的，你给我日志吧，可能是其他问题

**Comment by endink** [comment]
如果方便，把这个视频文件也给我测试一下

**Comment by hellosorry** [comment]
> 看起来环境是 OK 的，你给志吧，可能是其他问题

**Comment by hellosorry** [comment]
[VActor.log](https://github.com/endink/VActor/files/10194781/VActor.log)

**Comment by endink** [comment]
我看到日志里你的文件名非常乱，先改一个简单的文件名，看看是不是这个问题

**Comment by hellosorry** [comment]
> 我看到日志里你的文件名非常乱，先改一个简单的文件名，看看是不是这个问题

我是打开软件就有那条红色错误信息，与文件关系估计不大

**Comment by endink** [comment]
红色是内存池超出，我找到你的问题了，我先紧急下架一下，手动安装 GStreamer 可以修复你的视频动补问题：

https://opensource.labijie.com/Mediapipe4u-plugin/Install/gstreamer.html

**Comment by hellosorry** [comment]
那我等你还是自己装这个依存文件

**Comment by endink** [comment]
你先自己安装吧，我今天可能处理不了了，按我给我的文档，安装一下就可以动补

**Comment by hellosorry** [comment]
> 你先自己安装吧，我今天可能处理不了了，按我给我的文档，安装一下就可以动补

不好的消息还是同样的
<img width="1080" alt="Snipaste_2022-12-09_21-26-24" src="https://user-images.githubusercontent.com/46017769/206712811-d8e2247a-8184-41bc-8a8e-d411ffeee96e.png">
问题

**Comment by endink** [comment]
我自己手动复制文件压缩了一个包，如果你已经安装 GStreamer 可以无视，如果你没有安装，最新的安装包我本地是没有问题，建议自己安装，更加可靠，GStreamer 打包非常复杂~~ Texture Pool 问题暂时无法修复，只能在下个版本中加入一个设置自己手动调节内存池，如果你没有发现显示错误请暂时无视

如无其他问题，我将关闭这个 issue，再次感谢反馈问题

**Comment by endink** [comment]
安装 GStreamer 只能解决你的视频动补问题，红字问题暂时无法解决，因为我找不到问题，下个版本我会给你一个配置，你或许要调到更大的内存池，默认是 1 个 G

**Comment by hellosorry** [comment]
好的，我已经安装GStreamer还是不能视频动补，等你更新，我继续用ThreeDPoseTracker把，我，估计我还是缺少什么依存文件或计算机设置问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anders ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 晚上9:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [endink/VActor] 软件报错，不能动普视频 (Issue #5)





 
安装 GStreamer 还是不能视频动补吗？红字问题暂时无法解决，因为我找不到问题，下个版本我会给你一个配置，你或许要调到更大的内存池，默认是 1 个 G

**Comment by endink** [comment]
嗯？你安装 GStreamer 然后重启软件还是不行吗？

**Comment by endink** [comment]
红字的错误并不会影响视频动补，只会造成某些地方显示残缺之类的

**Comment by hellosorry** [comment]
对的，还是同样的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anders ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 晚上9:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [endink/VActor] 软件报错，不能动普视频 (Issue #5)





 
嗯？你安装 GStreamer 然后重启软件还是不行吗？

**Comment by endink** [comment]
那再给我你的日志文件吧

**Comment by hellosorry** [comment]
但是，视频动补就一直0:0:00左右下角也没画面



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anders ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 晚上9:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [endink/VActor] 软件报错，不能动普视频 (Issue #5)





 
红字的错误并不会影响视频动补，只会造成某些地方显示残缺之类的

**Comment by endink** [comment]
那和红字错误没有关系，我刚才看你的日志文件是 GStreamer 报错了

**Comment by endink** [comment]
你日志里的错误是 Your GStreamer installation is missing a plug-in，这个错误一般是无法解码这个视频文件，或许你可以换一个视频文件再看一下

**Comment by hellosorry** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/VActor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月9日(星期五) 晚上9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/VActor] 软件报错，不能动普视频 (Issue #5)





 
那和红字错误没有关系，我刚才看你的日志文件是 GStreamer 报错了

**Comment by hellosorry** [comment]
好像报错挺多的，左上角，换了个视频后可以动补了，但导出一个不知道什么文件，


附件是日志文件


------------------ 原始邮件 ------------------
发件人: "Anders ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 晚上9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [endink/VActor] 软件报错，不能动普视频 (Issue #5)





 
你日志里的错误是 Your GStreamer installation is missing a plug-in，这个错误一般是无法解码这个视频文件，或许你可以换一个视频文件再看一下

**Comment by endink** [comment]
导出的是 BVH ，目前只支持 BVH，如果你无法处理BVH，或许这个软件确实对你没有什么用

**Comment by hellosorry** [comment]
好的，我以为文件输出有问题，我手动改名.BVH用blender可以打开动作数据，你这用的不是BVH标准骨骼吧？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anders ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 晚上10:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [endink/VActor] 软件报错，不能动普视频 (Issue #5)





 
导出的是 BVH ，目前只支持 BVH，如果你无法处理BVH，或许这个软件确实对你没有什么用

**Comment by endink** [comment]
BVH 没有标准骨骼，这个骨骼是你看到的 VRM 角色的骨骼，一般K帧不是用 Motion Builder 重定向到你自己的骨骼吗，用什么骨骼应该无所谓吧

**Comment by hellosorry** [comment]
好的，真的非常感谢如此美好的沟通和赐教过程，只要你发视频我肯定每个都是三连，希望哥哥越来越好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anders ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 晚上10:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [endink/VActor] 软件报错，不能动普视频 (Issue #5)





 
BVH 没有标准骨骼，这个骨骼是你看到的 VRM 角色的骨骼，一般K帧不是用 Motion Builder 重定向到你自己的骨骼吗，用什么骨骼应该无所谓吧

**Comment by endink** [comment]
不客气，反馈问题就是最大支持，再次感谢你的反馈，看球赛了😂

**Comment by hellosorry** [comment]
好的，巴西2：1格子军团




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anders ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 晚上10:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [endink/VActor] 软件报错，不能动普视频 (Issue #5)





 
不客气，反馈问题就是最大支持，再次感谢你的反馈，看球赛了😂

**Comment by endink** [comment]
最新版本已经扩大了纹理缓冲池，如果问题依旧，请重新打开这个 issue，先关闭了~ 对于特殊文件无法解析，我也无能为力，这全靠 GStreamer
